---

- name: check for nvidia_smi binary
  stat:
    path: '{{ nvidia_smi_path }}'
  register: nvidia_smi_binary
  ignore_errors: yes


- block:
  - name: capture nvidia_smi info
    command: '{{ nvidia_smi_path }} -q -x'
    register: nvidia_smi_info

  - name: set the collected nvidia_smi info as facts
    set_fact:
      stockpile_nvidia_smi:
        xml: "{{ nvidia_smi_info.stdout }}"
        error: "{{ nvidia_smi_info.stderr }}"
  when: nvidia_smi_binary.stat.exists

