---

- name: Get node info
  community.kubernetes.k8s_info:
    kind: Node
  register: node_info

- block:

  - name: Set node info as facts
    set_fact:
      stockpile_k8s_nodes: "{{ node_info.resources }}"

  when: node_info.resources
