---
  - name: check node
    command: "/usr/local/bin/kubectl --kubeconfig={{ kube_config }} cluster-info"
    register: cluster_status
    ignore_errors: true

  - block:
    
    - name: Get node info
      k8s_facts:
        kind: Node
        kubeconfig: "{{ kube_config }}"
      register: node_list

    - name: Set node info as facts
      set_fact:
        stockpile_k8s_nodes: "{{ node_list.resources }}"

    when: cluster_status is succeeded
