---
- hosts: all
  remote_user: "{{ host_remote_user }}"
  become: true
  roles:
    - openstack_common
    #- packages
    - cpu
    - cpu_vulnerabilities
    - kernel-debug
    - dmidecode
    - yum_repos
    - ceph
    - openshift-cluster-topology
    - openshift-nodes
    #- example
    #- example2
    - openstack_compute
    - openstack_nova
    - openstack_neutron
    - openstack_keystone
    - openstack_ceilometer
    - openstack_gnocchi
    - openstack_cinder
    - openstack_heat
    - openstack_mysql
    - openstack_rabbitmq
    - openstack_glance
    - openstack_undercloud

- hosts: stockpile
  gather_facts: false
  remote_user: "{{ stockpile_user }}"
  roles:
    - dump-facts
