---
- hosts: all
  remote_user: "{{ host_remote_user }}"
  become: true
  roles:
    - common
    #- packages
    - cpu
    - cpu_vulnerabilities
    - kernel-debug
    - dmidecode
    - yum_repos
    - ceph
    - openshift-cluster-topology
    - openshift-nodes
    #- example
    #- example2
    - compute
    - nova
    - neutron
    - keystone
    - ceilometer
    - gnocchi
    - cinder
    - heat
    - mysql
    - rabbitmq
    - glance
    - undercloud

- hosts: stockpile
  gather_facts: false
  remote_user: "{{ stockpile_user }}"
  roles:
    - dump-facts
