---

# This shouldn't be needed if ansible version >=2.5, but since browbeat has pinned
# version 2.4.1

- name: Get user's home directory
  shell: "getent passwd {{ ansible_user }} | cut -d: -f6"
  register: user_homedir

# ansible_env.HOME should've worked here
- name: Check that undercloud is installed
  stat: path={{ user_homedir.stdout }}/undercloud.conf
  register: undercloud_conf

- name: Parse config
  become: true
  script: ../openstack_common/files/openstack-config-parser.py undercloud
  when: undercloud_conf.stat.exists
  register: undercloud_data

# These won't be needed because stockpile wil run mysql and rabbitmq role against UC as well.
# - name: Get max_connections on the database
#   shell: mysql -e "show variables like 'max_connections';" | grep max_connections | awk '{print $2}'
#   register: max_conn
#   ignore_errors: true
#   when: undercloud_conf.stat.exists
#
# - name: Set max database connections
#   set_fact:
#     openstack_mysql_max_connections: "{{ max_conn.stdout }}"
#   when: undercloud_conf.stat.exists
#
# - name : Get file descriptors for the mysql process
#   shell: cat /proc/$(pgrep mysqld_safe)/limits | grep "open files" | awk '{print $4}'
#   register: mysql_desc
#   when: undercloud_conf.stat.exists
#
# - name: Set file descriptors fact for mysql
#   set_fact:
#     openstack_mysql_file_descriptors: "{{ mysql_desc.stdout }}"
#   when: undercloud_conf.stat.exists
#
# - name : Get rabbitmq file descriptors
#   shell: rabbitmqctl status | grep total_limit |  awk -F',' '{print $2}' | sed 's/.$//'
#   register: rabbitmq_desc
#   ignore_errors: true
#   when: undercloud_conf.stat.exists


# ansible_env.HOME should've worked here
- name: Get Controller Nodes number
  shell: source {{ user_homedir.stdout }}/stackrc; nova list | grep controller | grep ACTIVE | wc -l
  register: controller_count
  when: undercloud_conf.stat.exists

- name: Get Compute Nodes number
  shell: source {{ user_homedir.stdout }}/stackrc; nova list | grep compute | grep ACTIVE | wc -l
  register: compute_count
  when: undercloud_conf.stat.exists

- name: setting fact
  set_fact:
    stockpile_openstack_undercloud: "{{ undercloud_data.stdout }}"
    stockpile_osp_enviroment:
      osp_controllers_number: "{{ controller_count.stdout }}"
      osp_computes_number: "{{ compute_count.stdout }}"
  when: undercloud_data is succeeded and undercloud_conf.stat.exists
