---
- hosts: compute
  remote_user: "{{ host_remote_user }}"
  become: true
  roles:
    - common
    - compute

- hosts: controller
  remote_user: "{{ host_remote_user }}"
  become: true
  roles:
    - common
    - nova
    - neutron
    - keystone
    - ceilometer
    - gnocchi
    - cinder
    - heat
    - mysql
    - rabbitmq
    - glance

- hosts: undercloud
  remote_user: "{{ local_remote_user }}"
  become: true
  roles:
    - common
    - undercloud

- hosts: all
  remote_user: root
  become: true
  roles:
    - collect_packages

- hosts: browbeat
  remote_user: "{{ browbeat_user }}"
  roles:
    - dump-facts
