---
# Checking if dmide is present
- name: Verify Dmidecode
  package:
    name: dmidecode
    state: present

- name: Run dmidecode
  command: dmidecode --quiet
  become: true
  changed_when: false
  register: dmide_run

- name: storing dmidecode output
  set_fact:
    stockpile_dmidecode: "{{ dmide_run.stdout }}"
