---
# Checking if dmide is present
- name: Verify Dmidecode
  package:
    name: dmidecode
    state: present

- name: Run dmidecode
  command: dmidecode --quiet
  register: dmide_run

- name: Storing the output of dmidecode
  set_fact:
    stockpile_dmidecode: "{{ dmide_run.stdout }}"
