---
# This role needs to be looked into as for RHOSP13 this doesn't collect anything
- name : Get rabbitmq file descriptors
  shell: rabbitmqctl status | grep file_descriptors | awk -F',' '{print $3}' | sed 's/.$//'
  register: rabbitmq_desc
  ignore_errors: true
  when: containers is not defined

- name: Set rabbitmq file descriptors
  set_fact:
    stockpile_openstack_rabbitmq_file_descriptors: "{{ rabbitmq_desc.stdout }}"
  when: rabbitmq_desc is succeeded and containers is not defined and rabbitmq_desc.stdout != ""

- name : Get rabbitmq file descriptors - containers
  shell: "{{ container_cli }} exec rabbitmq rabbitmqctl status | grep total_limit | awk -F',' '{print $2}'| sed 's/.$//'"
  register: rabbitmq_desc
  ignore_errors: true
  when: containers is defined

- name: Set rabbitmq file descriptors
  set_fact:
    stockpile_openstack_rabbitmq_file_descriptors: "{{ rabbitmq_desc.stdout }}"
  when: rabbitmq_desc is succeeded and containers is defined and rabbitmq_desc.stdout != ""
