---
  - name: check node
    command: "/usr/local/bin/kubectl --kubeconfig={{ kube_config }} cluster-info"
    register: cluster_status
    ignore_errors: true

  - block:
    
    - name: Get pod info
      k8s_facts:
        kind: Pod
        kubeconfig: "{{ kube_config }}"
      register: pod_list

    - name: Set info as facts
      set_fact:
        stockpile_k8s_pods: "{{ pod_list.resources }}"

    when: cluster_status is succeeded
