---

- name: Check if oc client is installed
  command: which oc
  register: oc_installed
  ignore_errors: yes

- block:
  - name: Get ocp network operator
    command: oc get networks.operator.openshift.io cluster -o json
    register: ocp_network_operator

  - name: Get ocp dns config
    command: oc get dns cluster -o json
    register: ocp_dns

  - name: Get network attachment definitions
    command: oc get network-attachment-definitions --all-namespaces -o json
    register: ocp_net_attachments

  - name: Set network operator
    set_fact:
      stockpile_ocp_network_operator: "{{ ocp_network_operator.stdout }}"

  - name: Set dns config
    set_fact:
      stockpile_ocp_dns: "{{ ocp_dns.stdout }}"

  - name: Set network attachment deffinitions
    set_fact:
      stockpile_ocp_net_attachments: "{{ ocp_net_attachments.stdout | from_json | json_query('items') }}"

  when: oc_installed.rc == 0
