---

- name: Check if oc client is installed
  command: which oc
  register: oc_installed
  ignore_errors: yes

- name: Check if kubeconfig exists
  stat:
    path: "{{ ansible_env.HOME }}/.kube/config"
  register: kubeconfig

- block:
  - name: Get ocp network operator
    command: oc get networks.operator.openshift.io cluster -o json
    register: ocp_network_operator

  - name: Get ocp dns config
    command: oc get dns cluster -o json
    register: ocp_dns

  - name: Get network attachment definitions
    command: oc get network-attachment-definitions --all-namespaces -o json
    register: ocp_net_attachments

  - name: Set network operator
    set_fact:
      stockpile_ocp_network_operator: "{{ ocp_network_operator.stdout }}"
    when: ocp_network_operator.rc == 0

  - name: Set dns config
    set_fact:
      stockpile_ocp_dns: "{{ ocp_dns.stdout }}"
    when: ocp_dns.rc == 0

  - name: Set network attachment deffinitions
    set_fact:
      stockpile_ocp_net_attachments: "{{ ocp_net_attachments.stdout | from_json | json_query('items') }}"
    when: ocp_net_attachments.rc == 0

  when: ( oc_installed.rc == 0 and kubeconfig.stat.exists )
