---

- name: see if ceph installed
  command: "rpm -q ceph-common"
  ignore_errors: true
  register: ceph_present

- block:
    - name: ceph version
      command: "ceph -f json version"
      register: ceph_version

    - name: ceph osd tree
      command: "ceph -f json osd tree"
      register: ceph_osd_tree

    - name: ceph -s
      command: "ceph -f json status"
      register: ceph_status

    - name: ceph osd pool ls detail
      command: "ceph -f json osd pool ls detail"
      register: ceph_osd_pool_ls_detail

    - name: ceph fs ls
      command: "ceph -f json fs ls"
      register: ceph_fs_ls

    - name: ceph mon_status
      command: "ceph mon_status"
      register: ceph_mon_status

    - name: ceph mds stat
      command: "ceph -f json mds stat"
      register: ceph_mds_stat

    - name: ceph osd crush rule dump
      command: "ceph -f json osd crush rule dump"
      register: ceph_osd_crush_rule_dump

    - name: ceph osd crush dump
      command: "ceph -f json osd crush dump"
      register: ceph_osd_crush_dump

    # this task injects all the variables with a ST_ prefix
    # so that machine_facts.json displays them properly

    - name: Set ceph collection as facts
      set_fact:
        stockpile_ceph:
          version: "{{ ceph_version.stdout | from_json }}"
          osd_tree: "{{ ceph_osd_tree.stdout | from_json }}"
          status: "{{ ceph_status.stdout | from_json }}"
          osd_pool_ls_detail: "{{ ceph_osd_pool_ls_detail.stdout | from_json }}"
          fs_ls: "{{ ceph_fs_ls.stdout | from_json }}"
          mon_status: "{{ ceph_mon_status.stdout | from_json }}"
          mds_stat: "{{ ceph_mds_stat.stdout | from_json }}"
          osd_crush_rule_dump: "{{ ceph_osd_crush_rule_dump.stdout | from_json }}"
          osd_crush_dump: "{{ ceph_osd_crush_dump.stdout | from_json }}"
  ignore_errors: true
  when: ceph_present.rc == 0
