---

- name: Parse Ceilometer config
  become: true
  script: ../openstack_common/files/openstack-config-parser.py ceilometer
  ignore_errors: true
  register: ceilometer_data

- name: setting fact
  set_fact:
    stockpile_openstack_ceilometer: "{{ ceilometer_data.stdout }}"
  when: ceilometer_data is succeeded
