---

- name: Parse mistral config
  become: true
  script: ../openstack_common/files/openstack-config-parser.py mistral
  ignore_errors: true
  register: mistral_data

- name: setting fact
  set_fact:
    stockpile_openstack_mistral: "{{ mistral_data.stdout }}"
  when: mistral_data is succeeded
