---
- name: collect yum repos
  yum:
    list: repos
  register: yum_repos
  when: ansible_pkg_mgr == 'yum'

- name: storing the yum repos data
  set_fact:
    stockpile_yum_repos: "{{ yum_repos.results }}"
  when: yum_repos is not skipped

- name: collect dnf repos
  dnf:
    list: repos
  register: dnf_repos
  when: ansible_pkg_mgr == 'dnf'

- name: storing the dnf repos data
  set_fact:
    stockpile_dnf_repos: "{{ dnf_repos.results }}"
  when: dnf_repos is not skipped



