apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backpack
  namespace: backpack
spec:
  selector:
    matchExpressions:
      - key: app
        operator: NotIn
        values:
        - backpack
  template:
    metadata:
      labels:
        name: backpack
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: backpack
        image: quay.io/cloud-bulldozer/backpack:master
        imagePullPolicy: Always
#        securityContext:
#          privileged: true
      terminationGracePeriodSeconds: 30
